---
# Source: filebeat/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filebeat-filebeat-role-binding
  labels:
    app: "filebeat-filebeat"
    chart: "filebeat-8.5.1"
    heritage: "Helm"
    release: "filebeat"
roleRef:
  kind: Role
  name: filebeat-filebeat-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat-filebeat
  namespace: netwok-logging
