---
# Source: gitea/charts/postgresql/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: gitea-postgresql
  namespace: "gitea"
  labels:
    app.kubernetes.io/instance: gitea
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/version: 17.4.0
    helm.sh/chart: postgresql-16.4.14
type: Opaque
data:
  postgres-password: "RWhJMTdLc0RyQQ=="
  password: "Z2l0ZWE="
  # We don't auto-generate LDAP password when it's not provided as we do for other passwords
