---
# Source: prometheus/charts/alertmanager/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-alertmanager
  labels:
    helm.sh/chart: alertmanager-1.11.0
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/version: "v0.27.0"
    app.kubernetes.io/managed-by: Helm
  namespace: monitoring
automountServiceAccountToken: true
